<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class ExportHpmStructures extends Command
{
    protected $signature = 'hpm:export-structures
        {--out=resources/js/constants/structures.generated.ts : Output path for generated TS file}
        {--var=HPM_STRUCTURES : Name of the exported TS constant}
        {--schemas=HPM_SCHEMAS : Name of the exported Zod schemas object}
    ';

    protected $description = 'Export HPM structures (from config/hpm.php) to a TypeScript module with constants, Zod schemas, and types.';

    /** @var array<string,string> Key-path based schema overrides */
    protected array $overrides = [
        // IDs: überall als number().nullable()
        '*.id' => 'z.number().nullable()',

        // Enums (anpassen, wenn du andere Werte zulässt)
        'header.props.density'         => "z.enum(['default','prominent','comfortable','compact'])",
        'header.props.scroll_behavior' => "z.enum(['hide','elevate','default'])",
        'header.props.color'           => "z.enum(['first','second','third','transparent'])",
        'header.props.height'    => 'z.number().min(0).max(128).nullable()',
        'header.props.elevation' => 'z.number().min(0).max(24).nullable()',
        'footer.props.height'    => 'z.number().min(0).max(128).nullable()',
        'footer.props.elevation' => 'z.number().min(0).max(24).nullable()',
    ];

    public function handle(): int
    {
        $config     = config('hpm', []);
        $version    = (string)($config['version'] ?? '0.0.0');
        $structures = $config['structures'] ?? [];

        if (!is_array($structures)) {
            $this->error('config("hpm.structures") is not an array.');
            return 1;
        }

        $json = json_encode($structures, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        if ($json === false) {
            $this->error('Failed to encode structures to JSON');
            return 1;
        }

        // Zod-Schemas je Top-Level-Struktur generieren
        $schemasTsParts = [];
        foreach ($structures as $key => $value) {
            $schema = $this->generateZodSchema($value, [$key]);
            $schemasTsParts[] = "  {$this->tsSafeKey($key)}: {$schema}";
        }
        $schemasTs = implode(",\n", $schemasTsParts);

        // Per-Structure Types emittieren
        $varName     = $this->option('var');
        $schemasName = $this->option('schemas');
        $perTypes    = $this->emitPerStructureTypes(array_keys($structures), $schemasName);

        // TS Datei aufbauen
        $ts = <<<TS
// AUTO-GENERATED — do not edit manually
// Generated by: php artisan hpm:export-structures
// Source: config/hpm.php
// Version: {$version}

import { z } from "zod";

export const HPM_VERSION = "{$this->escapeTsString($version)}" as const;

export const {$varName} = {$json} as const;

// Zod schemas derived from PHP config shape with overrides + .strict()
export const {$schemasName} = {
{$schemasTs}
} as const;

// Inferred types:
export type HpmStructures = typeof {$varName};
export type HpmStructureKey = keyof HpmStructures;

// Per-structure types (zod inference):
{$perTypes}

// Helper accessors:
export const getStructure = <K extends HpmStructureKey>(key: K) => {$varName}[key];

// Optional runtime validation helper
export function validateStructure<K extends HpmStructureKey>(key: K, value: unknown) {
  const schema = ({$schemasName} as any)[key];
  if (!schema) throw new Error("No schema for key: " + String(key));
  return (schema as z.ZodTypeAny).parse(value);
}

// Quality-of-life helpers
export type DeepReadonly<T> = { readonly [K in keyof T]: DeepReadonly<T[K]> };
export const {$varName}_RO: DeepReadonly<typeof {$varName}> = {$varName};

export function cloneStructure<K extends HpmStructureKey>(key: K): HpmStructures[K] {
  return typeof structuredClone === 'function'
    ? structuredClone({$varName}[key])
    : JSON.parse(JSON.stringify({$varName}[key]));
}
TS;

        $out = $this->option('out');
        File::ensureDirectoryExists(dirname($out));
        File::put($out, $ts);

        $this->info("✅ Wrote {$out}");
        return 0;
    }

    // ---------------------------------------------------------------------
    // Schema-Generator
    // ---------------------------------------------------------------------

    /**
     * Generiert ein Zod-Schema für den gegebenen PHP-Wert.
     * - Nutzt $this->overrides anhand des Key-Pfads (z.B. 'header.props.density').
     * - Objekte werden .strict() gemacht.
     * - Arrays: versucht Element-Schema aus erstem Element abzuleiten, sonst z.any()
     */
    protected function generateZodSchema($value, array $path): string
    {
        // 1) Override?
        if ($override = $this->matchOverride($path)) {
            return $override;
        }

        // 2) Primitive Typen
        if (is_string($value)) return 'z.string()';
        if (is_int($value) || is_float($value)) return 'z.number()';
        if (is_bool($value)) return 'z.boolean()';
        if (is_null($value)) return 'z.any().nullable()'; // generisch null

        // 3) Arrays
        if (is_array($value)) {
            if ($this->isAssoc($value)) {
                // ---- Objekt ----
                $lines = [];
                foreach ($value as $k => $v) {
                    $childPath = array_merge($path, [$k]);
                    $lines[] = '  ' . $this->tsSafeKey($k) . ': ' . $this->generateZodSchema($v, $childPath);
                }

                // WICHTIG: geschweifte Klammern um die Felder
                if (!empty($lines)) {
                    $inner = "{\n" . implode(",\n", $lines) . "\n}";
                } else {
                    $inner = "{}";
                }

                return "z.object({$inner}).strict()";
            } else {
                // ---- Liste ----
                if (count($value) > 0) {
                    $first = reset($value);
                    $elemSchema = $this->generateZodSchema($first, array_merge($path, ['0']));
                    return "z.array({$elemSchema})";
                }
                return 'z.array(z.any())';
            }
        }

        // Fallback
        return 'z.any()';
    }


    protected function isAssoc(array $arr): bool
    {
        $i = 0;
        foreach (array_keys($arr) as $k) {
            if ($k !== $i++) return true;
        }
        return false;
    }

    /**
     * Versucht, für den gegebenen Pfad ein Override zu finden.
     * Unterstützt Wildcards mit '*', z.B. '*.id'
     */
    protected function matchOverride(array $path): ?string
    {
        $dot = implode('.', $path);

        // exakt zuerst
        if (array_key_exists($dot, $this->overrides)) {
            return $this->overrides[$dot];
        }

        // Wildcards prüfen
        foreach ($this->overrides as $pattern => $schema) {
            if ($this->wildcardMatch($pattern, $dot)) {
                return $schema;
            }
        }
        return null;
    }

    protected function wildcardMatch(string $pattern, string $value): bool
    {
        // sehr einfache Wildcard-Umsetzung: '*' ersetzt beliebigen Abschnitt ohne Punkte
        $regex = '/^' . str_replace(['*', '.'], ['[^.]+', '\.'], preg_quote($pattern, '/')) . '$/u';
        return (bool)preg_match($regex, $value);
    }

    protected function tsSafeKey($key): string
    {
        if (preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', (string)$key)) {
            return (string)$key;
        }
        return json_encode((string)$key, JSON_UNESCAPED_SLASHES);
    }

    protected function escapeTsString(string $s): string
    {
        return str_replace('"', '\\"', $s);
    }

    protected function emitPerStructureTypes(array $keys, string $schemasName): string
    {
        $lines = [];
        foreach ($keys as $key) {
            $safeType = preg_replace('/[^A-Za-z0-9_]/', '_', (string)$key);
            $typeName = ucfirst($safeType);
            // dot-access (Keys sind bei dir valide): HPM_SCHEMAS.header
            $lines[] = "export type {$typeName} = z.infer<typeof {$schemasName}." . $this->tsSafeKey($key) . ">;";
        }
        return implode("\n", $lines);
    }
}
