// AUTO-GENERATED — do not edit manually
// Generated by: php artisan hpm:export-structures
// Source: config/hpm.php
// Version: 0.0.4

import { z } from "zod";

export const HPM_VERSION = "0.0.4" as const;

export const HPM_STRUCTURES = {
    "homepage": {
        "index": {
            "id": null
        },
        "fonts": {
            "fontset": "default"
        },
        "colors": {
            "colorset": "default"
        }
    },
    "index": {
        "header": {
            "id": null,
            "is_visible": true
        },
        "content": [],
        "footer": {
            "id": null,
            "is_visible": true
        }
    },
    "header": {
        "props": {
            "border": false,
            "color": "first",
            "density": "default",
            "elevation": 0,
            "flat": true,
            "height": null,
            "height_row_1": null,
            "scroll_behavior": "hide"
        },
        "rows": {
            "count": 1,
            "row_1": {
                "desktop": {
                    "fluid": false,
                    "max_width": null,
                    "color": "transparent",
                    "columns": {
                        "count": 3,
                        "col_1": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_2": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_3": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        }
                    }
                },
                "tablet": {
                    "fluid": false,
                    "max_width": null,
                    "color": "transparent",
                    "columns": {
                        "count": 3,
                        "col_1": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_2": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_3": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        }
                    }
                },
                "handy": {
                    "fluid": false,
                    "max_width": null,
                    "color": "transparent",
                    "columns": {
                        "count": 3,
                        "col_1": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_2": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_3": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        }
                    }
                }
            },
            "row_2": {
                "desktop": {
                    "fluid": false,
                    "max_width": null,
                    "color": "transparent",
                    "columns": {
                        "count": 3,
                        "col_1": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_2": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_3": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        }
                    }
                },
                "tablet": {
                    "fluid": false,
                    "max_width": null,
                    "color": "transparent",
                    "columns": {
                        "count": 3,
                        "col_1": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_2": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_3": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        }
                    }
                },
                "handy": {
                    "fluid": false,
                    "max_width": null,
                    "color": "transparent",
                    "columns": {
                        "count": 3,
                        "col_1": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_2": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        },
                        "col_3": {
                            "justify": "justify-start",
                            "has_menu": false,
                            "menu_id": null,
                            "menu_name": null,
                            "has_image": false,
                            "invert_image": false,
                            "image": null,
                            "image_height": 32,
                            "image_width": null,
                            "has_text": true,
                            "text": "Homepagemaker",
                            "text_variant": "subcontent"
                        }
                    }
                }
            }
        }
    },
    "footer": {
        "props": {
            "border": false,
            "color": "first",
            "elevation": 0,
            "flat": true,
            "height": 0
        }
    }
} as const;

// Zod schemas derived from PHP config shape with overrides + .strict()
export const HPM_SCHEMAS = {
  homepage: z.object({
  index: z.object({
  id: z.any().nullable()
}).strip(),
  fonts: z.object({
  fontset: z.string()
}).strip(),
  colors: z.object({
  colorset: z.string()
}).strip()
}).strip(),
  index: z.object({
  header: z.object({
  id: z.any().nullable(),
  is_visible: z.boolean()
}).strip(),
  content: z.array(z.any()),
  footer: z.object({
  id: z.any().nullable(),
  is_visible: z.boolean()
}).strip()
}).strip(),
  header: z.object({
  props: z.object({
  border: z.boolean(),
  color: z.enum(['first','second','third','transparent']),
  density: z.enum(['default','prominent','comfortable','compact']),
  elevation: z.number().min(0).max(24).nullable(),
  flat: z.boolean(),
  height: z.number().min(0).max(128).nullable(),
  height_row_1: z.number().min(0).max(128).nullable(),
  scroll_behavior: z.enum(['hide','elevate','default'])
}).strip(),
  rows: z.object({
  count: z.number(),
  row_1: z.object({
  desktop: z.object({
  fluid: z.boolean(),
  max_width: z.any().nullable(),
  color: z.string(),
  columns: z.object({
  count: z.number(),
  col_1: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_2: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_3: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip()
}).strip()
}).strip(),
  tablet: z.object({
  fluid: z.boolean(),
  max_width: z.any().nullable(),
  color: z.string(),
  columns: z.object({
  count: z.number(),
  col_1: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_2: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_3: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip()
}).strip()
}).strip(),
  handy: z.object({
  fluid: z.boolean(),
  max_width: z.any().nullable(),
  color: z.string(),
  columns: z.object({
  count: z.number(),
  col_1: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_2: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_3: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip()
}).strip()
}).strip()
}).strip(),
  row_2: z.object({
  desktop: z.object({
  fluid: z.boolean(),
  max_width: z.any().nullable(),
  color: z.string(),
  columns: z.object({
  count: z.number(),
  col_1: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_2: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_3: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip()
}).strip()
}).strip(),
  tablet: z.object({
  fluid: z.boolean(),
  max_width: z.any().nullable(),
  color: z.string(),
  columns: z.object({
  count: z.number(),
  col_1: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_2: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_3: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip()
}).strip()
}).strip(),
  handy: z.object({
  fluid: z.boolean(),
  max_width: z.any().nullable(),
  color: z.string(),
  columns: z.object({
  count: z.number(),
  col_1: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_2: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip(),
  col_3: z.object({
  justify: z.string(),
  has_menu: z.boolean(),
  menu_id: z.any().nullable(),
  menu_name: z.any().nullable(),
  has_image: z.boolean(),
  invert_image: z.boolean(),
  image: z.any().nullable(),
  image_height: z.number(),
  image_width: z.any().nullable(),
  has_text: z.boolean(),
  text: z.string(),
  text_variant: z.string()
}).strip()
}).strip()
}).strip()
}).strip()
}).strip()
}).strip(),
  footer: z.object({
  props: z.object({
  border: z.boolean(),
  color: z.string(),
  elevation: z.number().min(0).max(24).nullable(),
  flat: z.boolean(),
  height: z.number().min(0).max(128).nullable()
}).strip()
}).strip()
} as const;

// Inferred types:
export type HpmStructures = typeof HPM_STRUCTURES;
export type HpmStructureKey = keyof HpmStructures;

// Per-structure types (zod inference):
export type Homepage = z.infer<typeof HPM_SCHEMAS.homepage>;
export type Index = z.infer<typeof HPM_SCHEMAS.index>;
export type Header = z.infer<typeof HPM_SCHEMAS.header>;
export type Footer = z.infer<typeof HPM_SCHEMAS.footer>;

// Helper accessors:
export const getStructure = <K extends HpmStructureKey>(key: K) => HPM_STRUCTURES[key];

// Optional runtime validation helper
export function validateStructure<K extends HpmStructureKey>(key: K, value: unknown) {
  const schema = (HPM_SCHEMAS as any)[key];
  if (!schema) throw new Error("No schema for key: " + String(key));
  return (schema as z.ZodTypeAny).parse(value);
}

// Quality-of-life helpers
export type DeepReadonly<T> = { readonly [K in keyof T]: DeepReadonly<T[K]> };
export const HPM_STRUCTURES_RO: DeepReadonly<typeof HPM_STRUCTURES> = HPM_STRUCTURES;

export function cloneStructure<K extends HpmStructureKey>(key: K): HpmStructures[K] {
  return typeof structuredClone === 'function'
    ? structuredClone(HPM_STRUCTURES[key])
    : JSON.parse(JSON.stringify(HPM_STRUCTURES[key]));
}